In [2]:
import os
import sys
import torch
import torch.nn as nn

In [11]:
# analysis parameters

dir = "/notebooks/learningFile/dna/analysis/test1"
idx = 0
embedding_output = torch.load(os.path.join(dir, f"embedding_output_{idx}.pt"))
embedding_output = embedding_output.cpu().detach().numpy()

rotary_pos_emb = torch.load(os.path.join(dir, f"rotary_pos_emb_{idx}.pt"))
rotary_pos_emb = rotary_pos_emb.cpu().detach().numpy()

In [16]:
# count the number of each values in the embedding_output
import numpy as np

unique, counts = np.unique(embedding_output[0], return_counts=True)
np.asarray((unique, counts)).T

array([[-0.37695312,  1.        ],
       [-0.35546875, 15.        ],
       [-0.33007812,  1.        ],
       ...,
       [ 0.20214844,  1.        ],
       [ 0.20898438,  1.        ],
       [ 0.21875   ,  1.        ]], shape=(1872, 2))

In [18]:
embedding_output[0]

array([[-0.10791016, -0.15332031, -0.03442383, ..., -0.06054688,
         0.03442383,  0.0402832 ],
       [-0.01806641,  0.00027275, -0.03320312, ..., -0.00717163,
        -0.0234375 , -0.01141357],
       [-0.0201416 ,  0.00068665,  0.01074219, ..., -0.00708008,
        -0.00964355, -0.00860596],
       ...,
       [-0.01300049,  0.02709961, -0.03540039, ..., -0.00897217,
        -0.00386047,  0.00074768],
       [ 0.02197266, -0.00070953,  0.01708984, ..., -0.00689697,
        -0.01153564, -0.02307129],
       [ 0.00891113, -0.06591797, -0.05737305, ..., -0.04345703,
         0.1171875 ,  0.03076172]], shape=(72, 1024), dtype=float32)

In [20]:
rotary_pos_emb[1]

array([[[1.0000000e+00, 7.4989420e-01, 5.6234133e-01, 4.2169651e-01,
         3.1622776e-01, 2.3713736e-01, 1.7782794e-01, 1.3335215e-01,
         1.0000000e-01, 7.4989416e-02, 5.6234129e-02, 4.2169653e-02,
         3.1622779e-02, 2.3713736e-02, 1.7782794e-02, 1.3335215e-02,
         9.9999998e-03, 7.4989423e-03, 5.6234132e-03, 4.2169648e-03,
         3.1622779e-03, 2.3713738e-03, 1.7782794e-03, 1.3335214e-03,
         1.0000000e-03, 7.4989424e-04, 5.6234130e-04, 4.2169649e-04,
         3.1622779e-04, 2.3713738e-04, 1.7782794e-04, 1.3335215e-04,
         1.0000000e+00, 7.4989420e-01, 5.6234133e-01, 4.2169651e-01,
         3.1622776e-01, 2.3713736e-01, 1.7782794e-01, 1.3335215e-01,
         1.0000000e-01, 7.4989416e-02, 5.6234129e-02, 4.2169653e-02,
         3.1622779e-02, 2.3713736e-02, 1.7782794e-02, 1.3335215e-02,
         9.9999998e-03, 7.4989423e-03, 5.6234132e-03, 4.2169648e-03,
         3.1622779e-03, 2.3713738e-03, 1.7782794e-03, 1.3335214e-03,
         1.0000000e-03, 7.4989424e